---

- name: Check the namespace
  assert:
    that:
    - stack_namespace|string|length > 0

# Bye bye...

- name: Deleting namespace '{{ stack_namespace }}'
  k8s:
    state: absent
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
    wait: yes
