---
language: python
python:
- '3.8'
install:
- pip install -r build-requirements.txt
- pip install -r requirements.txt
- ansible-galaxy install -r requirements.yaml
- ansible-galaxy collection install -r collection-requirements.yaml
script:
- yamllint .
- find . -type f -name '*.yaml.j2' -exec yamllint {} \;
- sphinx-build -Eab html docs/source docs/build/html
