---
kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: letsencrypt-nginx-production
spec:
  acme:
    email: <EMAIL-ADDRESS>
    privateKeySecretRef:
      name: letsencrypt-nginx-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
