---

- name: Check key variables
  assert:
    that:
    - replicator_a_nfs_server|string|length > 0
    - replicator_a_nfs_server|string != 'SetMe'
    - replicator_a_nfs_path|string|length > 0
    - replicator_a_nfs_path|string != 'SetMe'
    - replicator_b_pvc_name|string|length > 0
    - replicator_b_pvc_name|string != 'SetMe'

- name: Check direction
  assert:
    that: replicate_direction_fact|string in ['AtoB', 'BtoA']

# The namespace (project) and PVC claim must exist.

- name: Check the namespace ({{ stack_namespace_fact }})
  assert:
    that:
    - stack_namespace_fact|string|length > 0

- name: Get the namespace
  k8s_info:
    kind: Namespace
    name: "{{ stack_namespace_fact }}"
  register: n_result

- name: Assert namepsace exists
  assert:
    that: n_result.resources|length == 1

- name: Get the PVC
  k8s_info:
    kind: PersistentVolumeClaim
    namespace: "{{ stack_namespace_fact }}"
    name: "{{ replicator_b_pvc_name }}"
  register: pvc_result

- name: Assert PVC exists
  assert:
    that: pvc_result.resources|length == 1

# Run Job or CronJob

- name: Run Job
  include_tasks: deploy-job.yaml
  when: replicator_schedule|string|length == 0

- name: Run CronJob
  include_tasks: deploy-cronjob.yaml
  when: replicator_schedule|string|length > 0
