---

# Called (normally) to authenticate with OpenShift.
# At the end of this play two variables are set,
# the kubernetes API host and an API key.

- name: Log in to OpenShift (obtain access token)
  k8s_auth:
    host: "{{ okd_master_hostname }}"
    username: "{{ okd_admin }}"
    password: "{{ okd_admin_password }}"
  register: k8s_auth_results

- name: Set API key
  set_fact:
    k8s_auth_host: "{{ okd_master_hostname }}"
    k8s_auth_api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
