---

# Set one of 'developer stack name' (typically 'default')
# or 'production stack namespace'.
#
# The direction replica direction is based on which variable is set.
# If 'stack_name' is used the direction will be 'AtoB',
# otherwise it's 'BtoA'
replicator_stack_name: ''
replicator_production_stack_ns: ''

# Details of the statically assigned replica volume (on an NFS server)
# (volume-a)
replicator_a_nfs_server: SetMe
replicator_a_nfs_path: SetMe
# Details of the PVC to copy from or copy into (based on direction)
# (volume-b). Typically 'media' for a stack.
replicator_b_pvc_name: SetMe
