---
kind: Namespace
apiVersion: v1
metadata:
  name: im-k8s-admin
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: im-k8s-admin
  namespace: im-k8s-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: im-k8s-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: im-k8s-admin
  namespace: im-k8s-admin
