---

- name: Check key variables
  assert:
    that:
    - loader_data_origin|string|length > 0
    - loader_data_origin|string != 'SetMe'

# Include sensitive (encrypted) material.

- name: Include sensitive variables
  include_vars:
    file: sensitive.vault

# The namespace (project),
# the media volume claim
# and a database secret must exist.

- name: Check the namespace ({{ stack_namespace }})
  assert:
    that:
    - stack_namespace|string|length > 0

- name: Get the namespace
  k8s_info:
    kind: Namespace
    name: "{{ stack_namespace }}"
  register: n_result

- name: Assert namepsace exists
  assert:
    that: n_result.resources|length == 1

- name: Get the media PVC
  k8s_info:
    kind: PersistentVolumeClaim
    namespace: "{{ stack_namespace }}"
    name: media
  register: pvc_result

- name: Assert media PVC exists
  assert:
    that: pvc_result.resources|length == 1

- name: Get the database secrets
  k8s_info:
    kind: Secret
    namespace: "{{ stack_namespace }}"
    name: database
  register: s_result

- name: Assert database secrets exist
  assert:
    that: s_result.resources|length == 1

- name: Launch the loader ({{ loader_type }})
  include_tasks: deploy-{{ loader_type }}.yaml
