---

- name: Check loader-specific variables
  assert:
    that:
    - loader_type|string == 's3'

- name: Remove any existing loader Job ({{ stack_namespace }})
  k8s:
    state: absent
    definition: "{{ lookup('template', 'job-{{ loader_type }}.yaml.j2') }}"
    wait: yes

- name: Launching new loader Job
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - secret
  - job-{{ loader_type }}

# Wait for the loader to complete

- name: Wait for loader Job
  k8s_info:
    kind: Job
    namespace: "{{ stack_namespace }}"
    name: {{ loader_type }}-loader
  register: result
  until: >-
    result.resources[0].status.completionTime is defined
    or result.resources[0].status.failed is defined
  delay: 60
  retries: "{{ (loader_timeout_minutes|int * 60 / 60)|int }}"

- name: Display loader Job status
  debug:
    var: result.resources[0].status

- name: Assert loader Job success
  assert:
    that:
    - result.resources[0].status.succeeded is defined
    - result.resources[0].status.succeeded == 1
    - result.resources[0].status.failed is not defined
