---

# Set one of 'developer stack name' (typically 'default')
# or (for production/staging) the 'stack_ns'.
replicator_stack_name: ''
replicator_stack_ns: ''

# The replicator type - one of 'backup' or 'recovery'
replicator_type: SetMe
# The replication (backup/recovery) schedule.
# If the schedule is empty the replication occurs only once (i.e. it's a Job)
replicator_schedule: '15 * * * *'

# Details of the NFS server
# and statically assigned replica volume (on an NFS server)
replicator_nfs_server: 130.246.213.182
replicator_nfs_path: /nfs/kubernetes-db-replica

# If 'replicator_schedule' is blank ('') the playbook will use this as the
# length of time to wait for the 'Job' to complete.
replicator_job_timeout_minutes: 15

# Do not stop if there's an error?
# Default 'no'.
replicator_recovery_do_not_stop_on_error: no
