---

# Set one of 'developer stack name' (typically 'default')
# or 'production stack namespace'.
replicator_stack_name: ''
replicator_stack_ns: ''

# The replicator type - one of 'backup' or 'recovery'
replicator_type: SetMe
# The replication (back/recovery) schedule.
# If the schedule is empty the replication occurs only once (i.e. it's a Job)
replicator_schedule: '15 * * * *'

# Details of the statically assigned replica volume (on an NFS server)
replicator_nfs_server: SetMe
replicator_nfs_path: SetMe
