---

# The replicator type - one of 'backup' or 'restore'
replicator_type: SetMe
# The replication (back/restore) schedule
replicator_schedule: '15 * * * *'

# Details of the statically assigned replica volume (on an NFS server)
replicator_nfs_server: SetMe
replicator_nfs_path: SetMe
