- name: Set new k8s (SELF) credentials
  hosts: localhost

  tasks:  

  # User should be set: -
  #
  # k8s_host (i.e. "https://1.2.3.4:6443")
  # k8s_self_token (i.e. "00000000")
  # k8s_tower_url_base (i.e. "https://example.com")
  - name: Check k8s (SELF) token
    ansible.builtin.assert:
      that:
      - k8s_host|string|length > 0
      - k8s_self_token|string|length > 0
      - k8s_tower_url_base|string|length > 0
      fail_msg: You must define suitable ansible variables

  - name: Set base URL of tower host
    awx.awx.tower_settings:
      name: TOWER_URL_BASE
      value: "{{ k8s_tower_url_base }}"

  - name: Add kubernetes credential
    awx.awx.tower_credential:
      name: "k8s (SELF)"
      credential_type: kubernetes
      description: "The replacement k8s API credntials"
      organization: "Diamond Light Source"
      inputs:
        name: "k8s (SELF)"
        host: "{{ k8s_host }}"
        api_key: "{{ k8s_self_token }}"
        verify_ssl: "{{ 'no'|bool }}"
