---

# Delete the destination directory?
# Basically invokes '--delete' to the replicator's rsync operation.
replicator_delete_destination: yes

# The service account (typically stack)
replicator_sa_name: stack

# Purpose label for the desired execution node
replicator_node_purpose: application

# The image you want to deploy,
# consisting of a (public) container registry,
# image and image tag...
#
# The reference image is maintained
# in our GitHub repo 'docker-volume-replicator'
replicator_image_registry: docker.io
replicator_image: informaticsmatters/volume-replicator
replicator_image_tag: latest

# Container requests/limits
replicator_cpu_limit: 1
replicator_mem_limit: 128Mi
replicator_cpu_request: 10m
replicator_mem_request: 128Mi
