---

- name: Add kubernetes credential
  awx.awx.tower_credential:
    name: "{{ item.name }}"
    credential_type: kubernetes
    description: "{{ item.description|default('', true) }}"
    organization: "{{ tower_org }}"
    inputs:
      name: "{{ item.name }}"
      host: "{{ item.host }}"
      api_key: "{{ item.api_key }}"
      verify_ssl: "{{ item.verify_ssl|bool }}"
