---

- name: Create job template extra_vars file ({{ item.name }}))
  copy:
    content: "{{ item.extra_vars }}"
    dest: /tmp/job-template-extra-vars.yaml
  when: item.extra_vars is defined

- name: Add job template ({{ item.name }}) (extra-vars)
  awx.awx.tower_job_template:
    name: "{{ item.name }}"
    job_type: run
    inventory: localhost
    project: "{{ item.project }}"
    playbook: "{{ item.playbook }}"
    ask_extra_vars: "{{ item.ask_extra_vars|default('no', true)|bool }}"
    extra_vars: "{{ lookup('file', '/tmp/job-template-extra-vars.yaml')|from_yaml }}"
  when: item.extra_vars is defined

- name: Add job template ({{ item.name }}) (no extra-vars)
  awx.awx.tower_job_template:
    name: "{{ item.name }}"
    job_type: run
    inventory: localhost
    project: "{{ item.project }}"
    playbook: "{{ item.playbook }}"
    ask_extra_vars: "{{ item.ask_extra_vars|default('no', true)|bool }}"
  when: item.extra_vars is not defined

- name: Associate extra credentials with the job template ({{ item.name }})
  command: >-
    tower-cli job_template associate_credential
    --job-template '{{ item.name }}'
    --credential '{{ job_template_credential }}'
  register: cmd_result
  changed_when: "'changed: false' not in cmd_result.stdout"
  loop: "{{ item.credentials }}"
  loop_control:
    loop_var: job_template_credential

- name: Associate labels with the job template ({{ item.name }})
  command: >-
    tower-cli job_template associate_label
    --job-template '{{ item.name }}'
    --label '{{ job_template_label }}'
  loop: "{{ item.labels }}"
  loop_control:
    loop_var: job_template_label
  when: item.labels is defined

- name: Grant team access to the job template ({{ item.name }})
  command: >-
    tower-cli role grant
    --team '{{ job_template_team }}'
    --type admin
    --job-template '{{ item.name }}'
  register: cmd_result
  changed_when: "'changed: false' not in cmd_result.stdout"
  loop: "{{ item.teams }}"
  loop_control:
    loop_var: job_template_team
  when: item.teams is defined
