---

- name: Add inventory (localhost)
  awx.awx.tower_inventory:
    name: "{{ item }}"
    organization: "{{ tower.organisation }}"
  loop:
  - localhost

- name: Grant team access to the inventory (localhost)
  command: >-
    tower-cli role grant
    --team '{{ item }}'
    --type admin
    --inventory 'localhost'
  register: cmd_result
  changed_when: "'changed: false' not in cmd_result.stdout"
  loop: "{{ tower.teams }}"
