---

- name: Add aws credential
  awx.awx.tower_credential:
    name: "{{ item.name }}"
    kind: aws
    description: "{{ item.description|default('', true) }}"
    organization: "{{ tower.organisation }}"
    username: "{{ item.aws_access_key_id }}"
    password: "{{ item.aws_secret_access_key }}"
