---

# First, add the AWS and kubernetes credentials that should
# be available as existing environment variables.
# That'll be an AWS credential used for the cluster
# and a Kubernetes credential for the control plane.

- name: Add cluster AWS credential (Rancher)
  include_tasks: add-credential-aws.yaml
  vars:
    item:
      name: aws (IAM User)
      description: The cluster AWS IAM User
      aws_access_key_id: "{{ tower_cluster_aws_access_key_id }}"
      aws_secret_access_key: "{{ tower_cluster_aws_secret_access_key }}"

- name: Add cluster k8s credential (IM/Demo)
  include_tasks: add-credential-kubernetes.yaml
  vars:
    item:
      name: k8s (Cluster)
      description: The cluster control plane credentials
      host: "{{ tower_cluster_k8s_auth_host }}"
      api_key: "{{ tower_cluster_k8s_auth_api_key }}"
      verify_ssl: "{{ tower_cluster_k8s_auth_veify_ssl }}"

# Now add credentials defined in the user's configuration.
# This is the list of definitions in the 'tower -> credentials' block...

- name: Add credentials
  include_tasks: add-credential-{{ item.kind }}.yaml
  loop: "{{ tower.credentials }}"
