---

- name: Add graph credential
  awx.awx.tower_credential:
    name: "{{ item.name }}"
    credential_type: graph
    description: "{{ item.description|default('', true) }}"
    organization: "{{ tower_org }}"
    inputs:
      hostname: "{{ item.host }}"
      password: "{{ item.password }}"
