---

- name: Add vault credential ({{ item.name }})
  awx.awx.tower_credential:
    name: "{{ item.name }}"
    description: "{{ item.description|default('', true) }}"
    kind: vault
    vault_password: "{{ item.vault_password }}"
    organization: "{{ tower.organisation }}"
