---

#-----------#
# localhost #
#-----------#
# A special 'localhost' host for the localhost inventory.
# Used by job templates that can run on the AWX server.

- name: Add localhost (AWX)
  awx.awx.tower_host:
    name: localhost
    description: localhost
    inventory: localhost
    variables:
      ansible_connection: local
