---

- name: Add kubernetes credential
  awx.awx.tower_credential:
    name: "{{ item.name }}"
    credential_type: kubernetes
    description: "{{ item.description|default('', true) }}"
    organization: "{{ tower.organisation }}"
    inputs:
      name: "{{ item.name }}"
      host: "{{ item.host }}"
      api_key: "{{ item.api_key }}"
      verify_ssl: "{{ item.verify_ssl|bool }}"

- name: Grant team access to the kubernetes credential ({{ item.name }})
  command: >-
    tower-cli role grant
    --team '{{ credential_team }}'
    --type admin
    --credential '{{ item.name }}'
  register: cmd_result
  changed_when: "'changed: false' not in cmd_result.stdout"
  loop: "{{ item.teams }}"
  loop_control:
    loop_var: credential_team
  when: item.teams is defined
