---

- name: Add project ({{ item.name }})
  awx.awx.tower_project:
    name: "{{ item.name }}"
    description: The {{ item.description }} Project
    organization: "{{ tower.organisation }}"
    scm_type: "{{ item.scm_type }}"
    scm_url: https://{{ item.scm_url }}.git
    scm_branch: "{{ item.scm_branch }}"
    scm_clean: yes
    scm_update_on_launch: yes

- name: Grant team access to the project ({{ item.name }})
  command: >-
    tower-cli role grant
    --team '{{ project_team }}'
    --type admin
    --project '{{ item.name }}'
  register: cmd_result
  changed_when: "'changed: false' not in cmd_result.stdout"
  loop: "{{ item.teams }}"
  loop_control:
    loop_var: project_team
  when: item.teams is defined

# Force an update for the project

- name: Force project updates ({{ item.name }})
  command: tower-cli project update --name '{{ item.name }}'
  register: cmd_result
  changed_when: "'changed: false' not in cmd_result.stdout"
