---

- name: Add vault credential ({{ item.name }})
  awx.awx.tower_credential:
    name: "{{ item.name }}"
    description: "{{ item.description|default('', true) }}"
    kind: vault
    vault_password: "{{ item.vault_password }}"
    organization: "{{ tower.organisation }}"

- name: Grant team access to the vault credential ({{ item.name }})
  command: >-
    tower-cli role grant
    --team '{{ credential_team }}'
    --type admin
    --credential '{{ item.name }}'
  register: cmd_result
  changed_when: "'changed: false' not in cmd_result.stdout"
  loop: "{{ item.teams }}"
  loop_control:
    loop_var: credential_team
  when: item.teams is defined
